// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LightHouse.Core.Generating.Native.NET45.Services.Templates
{
    using LightHouse.Core.Model;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class DataObjectTemplate : DataObjectTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Runtime.Serialization;\r\nusing System.Collections.Gene" +
                    "ric; \r\n\r\nusing LightHouse.Core;\r\nusing LightHouse.Core.Collections;\r\nusing Light" +
                    "House.Core.Localization;\r\n\r\nusing LightHouse.Model;\r\n\r\nnamespace ");
            
            #line 19 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
 if(Element.Domain != null && Element.Domain.Reference != null) { 
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 19 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.Domain.Reference));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 19 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
  }  
            
            #line default
            #line hidden
            this.Write("{\r\n\t[LightHouse.Core.Attributes.Contract(typeof(");
            
            #line 21 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.ShortName));
            
            #line default
            #line hidden
            this.Write("), true)]\r\n\tpublic class ");
            
            #line 22 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.ShortName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 22 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
 if(Element.Parent != null && Element.Parent.ShortName != null && Element.Parent.Domain != null && Element.Parent.Domain.Reference != null)
	{ 
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 23 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.Parent.Domain.Reference));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 23 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.Parent.ShortName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 24 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
  }  
            
            #line default
            #line hidden
            this.Write("\t{\r\n\t\tpublic ");
            
            #line 26 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.ShortName));
            
            #line default
            #line hidden
            this.Write("(LightHouse.Core.ContractObject contractObject, Boolean isProxy) : base(contractO" +
                    "bject, isProxy)\r\n\t\t{\r\n\t\t\tif(this.GetType() != typeof(EntityObject))\r\n\t\t\t{\r\n\t\t\t\tr" +
                    "eturn;\r\n\t\t\t}\r\n\r\n\t\t\tthis.proxyInformation = (ProxyInformation)new ");
            
            #line 33 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.ShortName));
            
            #line default
            #line hidden
            this.Write("ProxyInformation();\r\n\t\t\tthis.SetProxyInformation(isProxy);\r\n\t\t}\r\n\r\n\t\tpublic ");
            
            #line 37 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.ShortName));
            
            #line default
            #line hidden
            this.Write("(Boolean isProxy) : this(null, isProxy) { }\r\n\r\n\t\tpublic ");
            
            #line 39 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.ShortName));
            
            #line default
            #line hidden
            this.Write(" (ContractObject contractObject) : this(contractObject, false) { }\r\n\r\n\t\tpublic ");
            
            #line 41 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.ShortName));
            
            #line default
            #line hidden
            this.Write("() : this(false) { }\r\n\r\n\t");
            
            #line 43 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
 foreach (Value value in Element.Characteristics)
	{ 
		Type type = GenerateCodeService.GetTypeFromValue(value);
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprivate ");
            
            #line 47 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 47 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.ShortName.ToLower()));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tpublic virtual ");
            
            #line 48 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 48 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.ShortName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget \r\n\t\t\t{\r\n\t\t\t\tif (this.GetProxyInformation().");
            
            #line 52 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.ShortName));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t{\r\n\t\t\t\t\tLightHouse.Elite.Storage.Loader.UnProxy((DataObject)this, (ProxyIn" +
                    "formation)this.GetProxyInformation(), (IContractList<ElementPath>)new ContractLi" +
                    "st<ElementPath>()\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tnew ElementPath()\r\n\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\tPath = \"");
            
            #line 58 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.ShortName));
            
            #line default
            #line hidden
            this.Write("\"\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t});\r\n\t\t\t\t}\r\n\t\t\t\treturn ");
            
            #line 62 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.ShortName.ToLower()));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t\tset\r\n\t\t\t{\r\n\t\t\t\tthis.");
            
            #line 66 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.ShortName.ToLower()));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\tthis.GetProxyInformation().");
            
            #line 67 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.ShortName));
            
            #line default
            #line hidden
            this.Write(" = false;\r\n\t\t\t}\r\n\t\t}\r\n");
            
            #line 70 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\tprotected virtual ");
            
            #line 72 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.ShortName));
            
            #line default
            #line hidden
            this.Write("ProxyInformation GetProxyInformation()\r\n\t\t{\r\n\t\t\treturn (");
            
            #line 74 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.ShortName));
            
            #line default
            #line hidden
            this.Write("ProxyInformation)this.proxyInformation;\r\n\t\t}\r\n\r\n\t\tpublic class ");
            
            #line 77 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.ShortName));
            
            #line default
            #line hidden
            this.Write("ProxyInformation ");
            
            #line 77 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
 if(Element.Parent != null && Element.Parent.ShortName != null && Element.Parent.Domain != null && Element.Parent.Domain.Reference != null)
		{ 
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 78 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.Parent.Domain.Reference));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 78 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.Parent.ShortName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 78 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Element.Parent.ShortName));
            
            #line default
            #line hidden
            this.Write("ProxyInformation ");
            
            #line 78 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t{");
            
            #line 80 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
 foreach (Value value in Element.Characteristics){ 
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\tpublic Boolean ");
            
            #line 81 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.ShortName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }");
            
            #line 81 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Workspace\Private\Turneo\Products\LightHouse\Code\Core\Generating\Native\Code\Services\Templates\DataObjectTemplate.tt"

private global::LightHouse.Model.Element _ElementField;

/// <summary>
/// Access the Element parameter of the template.
/// </summary>
private global::LightHouse.Model.Element Element
{
    get
    {
        return this._ElementField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ElementValueAcquired = false;
if (this.Session.ContainsKey("Element"))
{
    this._ElementField = ((global::LightHouse.Model.Element)(this.Session["Element"]));
    ElementValueAcquired = true;
}
if ((ElementValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Element");
    if ((data != null))
    {
        this._ElementField = ((global::LightHouse.Model.Element)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class DataObjectTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
